### ISSUE TITLE
Client.__init__() got an unexpected keyword argument 'proxies'

### ISSUE THREAD

**Issue by aidando73** [meta-llama/llama-stack-client-python#54]
Issue from llama-stack-apps: https://github.com/meta-llama/llama-stack-apps/issues/131

Getting an error on httpx=0.28.0. Installing httpx=0.27.2 fixes it:

```
(llama-stack) ubuntu@168-138-112-243:~/1xa100-2/llama-stack-apps$ python -m examples.agents.hello localhost 5001
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/1xa100-2/llama-stack-apps/examples/agents/hello.py", line 78, in <module>
    fire.Fire(main)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/ubuntu/1xa100-2/llama-stack-apps/examples/agents/hello.py", line 17, in main
    client = LlamaStackClient(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/llama_stack_client/_client.py", line 108, in __init__
    super().__init__(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/llama_stack_client/_base_client.py", line 855, in __init__
    self._client = http_client or SyncHttpxClientWrapper(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/llama_stack_client/_base_client.py", line 753, in __init__
    super().__init__(**kwargs)
TypeError: Client.__init__() got an unexpected keyword argument 'proxies'
```

httpx maintainer replied that that proxies argument has been removed:

> Heya. That parameter became deprecated in 0.26.0, and was removed in 0.28.0.
If you could follow up with llama_stack_client to help their team get this resolved, that'd be helpful.
You can pin to httpx=0.27.2 in the meantime.

https://github.com/encode/httpx/discussions/3425

**Comment by yanxi0830** [comment]
Thanks for raising the issue, this have been fixed in the latest llama-stack-client-python versions!
